-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.author_aliases
(
    id serial NOT NULL,
    author_id integer NOT NULL,
    alias_name character varying(300) COLLATE pg_catalog."default" NOT NULL,
    normalized_alias character varying(300) COLLATE pg_catalog."default",
    source character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT author_aliases_pkey PRIMARY KEY (id),
    CONSTRAINT uq_author_alias UNIQUE (author_id, alias_name)
);

CREATE TABLE IF NOT EXISTS public.author_audit_log
(
    id serial NOT NULL,
    author_id integer,
    change_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    before_data jsonb,
    after_data jsonb,
    field_changes jsonb,
    source character varying(100) COLLATE pg_catalog."default",
    changed_by character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT author_audit_log_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.author_audit_log.change_type
    IS 'created | updated | merged_into | merged_from | verified | deleted';

CREATE TABLE IF NOT EXISTS public.author_conflicts
(
    id serial NOT NULL,
    author_id integer NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    existing_value text COLLATE pg_catalog."default",
    new_value text COLLATE pg_catalog."default",
    existing_source character varying(100) COLLATE pg_catalog."default",
    new_source character varying(100) COLLATE pg_catalog."default",
    resolved boolean NOT NULL,
    resolution character varying(50) COLLATE pg_catalog."default",
    resolved_at timestamp with time zone,
    resolved_by character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT author_conflicts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.author_institutions
(
    id serial NOT NULL,
    author_id integer NOT NULL,
    institution_id integer NOT NULL,
    start_year integer,
    end_year integer,
    is_current boolean DEFAULT true,
    CONSTRAINT author_institutions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_author_institution UNIQUE (author_id, institution_id)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    id serial NOT NULL,
    name character varying(300) COLLATE pg_catalog."default" NOT NULL,
    normalized_name character varying(300) COLLATE pg_catalog."default",
    orcid character varying(50) COLLATE pg_catalog."default",
    is_institutional boolean NOT NULL,
    field_provenance jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    external_ids jsonb DEFAULT '{}'::jsonb,
    verification_status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'auto_detected'::character varying,
    possible_duplicate_of integer,
    cedula character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.canonical_pub_open_data
(
    id serial NOT NULL,
    canonical_publication_id integer NOT NULL,
    open_data_record_id bigint NOT NULL,
    id_producto_pd text COLLATE pg_catalog."default",
    nme_clase_pd text COLLATE pg_catalog."default",
    nme_tipologia_pd text COLLATE pg_catalog."default",
    cod_grupo_gr text COLLATE pg_catalog."default",
    nme_grupo_gr text COLLATE pg_catalog."default",
    nme_convocatoria text COLLATE pg_catalog."default",
    ano_convo text COLLATE pg_catalog."default",
    match_score double precision NOT NULL,
    match_method character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'exact'::character varying,
    matched_at timestamp with time zone DEFAULT now(),
    nme_tipo_medicion_pd text COLLATE pg_catalog."default",
    CONSTRAINT canonical_pub_open_data_pkey PRIMARY KEY (id),
    CONSTRAINT uq_canon_open_data UNIQUE (canonical_publication_id, open_data_record_id)
);

CREATE TABLE IF NOT EXISTS public.canonical_publications
(
    id serial NOT NULL,
    doi character varying(255) COLLATE pg_catalog."default",
    pmid character varying(50) COLLATE pg_catalog."default",
    pmcid character varying(50) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default" NOT NULL,
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    journal_id integer,
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    institutional_authors_count integer NOT NULL,
    field_provenance jsonb,
    sources_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    estado_publicacion character varying(20) COLLATE pg_catalog."default" DEFAULT 'Avalado'::character varying,
    estado_publicacion_id integer DEFAULT 1,
    field_conflicts jsonb DEFAULT '{}'::jsonb,
    citations_by_source jsonb DEFAULT '{}'::jsonb,
    abstract text COLLATE pg_catalog."default",
    keywords text COLLATE pg_catalog."default",
    source_url character varying(1000) COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    publisher character varying(300) COLLATE pg_catalog."default",
    journal_coverage character varying(100) COLLATE pg_catalog."default",
    knowledge_area character varying(300) COLLATE pg_catalog."default",
    cine_code character varying(50) COLLATE pg_catalog."default",
    first_author character varying(300) COLLATE pg_catalog."default",
    corresponding_author character varying(300) COLLATE pg_catalog."default",
    coauthorships_count integer,
    CONSTRAINT canonical_publications_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.canonical_publications.field_provenance
    IS 'Dict campo→fuente. Ej: {''doi'':''openalex'',''source_journal'':''scopus''}';

COMMENT ON COLUMN public.canonical_publications.estado_publicacion
    IS 'Estado de la publicación: Avalado, Revisión, Rechazado';

COMMENT ON COLUMN public.canonical_publications.estado_publicacion_id
    IS 'Estado de la publicación: referencia a publicacion_estados (Avalado, Revisión, Rechazado)';

CREATE TABLE IF NOT EXISTS public.clasificacion_minciencias
(
    id serial NOT NULL,
    canonical_publication_id integer NOT NULL,
    nme_clase_pd character varying(200) COLLATE pg_catalog."default",
    nme_tipo_medicion_pd character varying(200) COLLATE pg_catalog."default",
    nme_tipologia_pd character varying(200) COLLATE pg_catalog."default",
    cod_grupo_gr character varying(20) COLLATE pg_catalog."default",
    nme_grupo_gr character varying(500) COLLATE pg_catalog."default",
    nme_convocatoria character varying(200) COLLATE pg_catalog."default",
    ano_convo character varying(20) COLLATE pg_catalog."default",
    match_score double precision,
    match_method character varying(20) COLLATE pg_catalog."default",
    classified_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT clasificacion_minciencias_pkey PRIMARY KEY (id),
    CONSTRAINT uq_clasif_pub_grupo UNIQUE (canonical_publication_id, cod_grupo_gr)
);

CREATE TABLE IF NOT EXISTS public.country
(
    code character(2) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    iso_3166_3 character(3) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT country_pkey PRIMARY KEY (code),
    CONSTRAINT country_iso_3166_3_key UNIQUE (iso_3166_3),
    CONSTRAINT country_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.cvlac_records
(
    id serial NOT NULL,
    cvlac_code character varying(100) COLLATE pg_catalog."default",
    cvlac_product_id character varying(255) COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    isbn character varying(30) COLLATE pg_catalog."default",
    product_type character varying(100) COLLATE pg_catalog."default",
    abstract text COLLATE pg_catalog."default",
    keywords text COLLATE pg_catalog."default",
    volume character varying(50) COLLATE pg_catalog."default",
    issue character varying(50) COLLATE pg_catalog."default",
    pages character varying(100) COLLATE pg_catalog."default",
    editorial character varying(300) COLLATE pg_catalog."default",
    visibility character varying(50) COLLATE pg_catalog."default",
    category character varying(10) COLLATE pg_catalog."default",
    research_group character varying(300) COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    publisher character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT cvlac_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.cvlac_records.product_type
    IS 'Tipo de producto CvLAC: Artículo, Libro, Capítulo, Patente, etc.';

COMMENT ON COLUMN public.cvlac_records.visibility
    IS 'Nacional, Internacional, No Aplica';

COMMENT ON COLUMN public.cvlac_records.category
    IS 'Categoría Minciencias: A1, A2, B, C';

COMMENT ON COLUMN public.cvlac_records.research_group
    IS 'Grupo de investigación al que se asocia el producto';

CREATE TABLE IF NOT EXISTS public.datos_abiertos_records
(
    id serial NOT NULL,
    datos_source_id character varying(255) COLLATE pg_catalog."default",
    dataset_id character varying(100) COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    isbn character varying(30) COLLATE pg_catalog."default",
    product_type character varying(100) COLLATE pg_catalog."default",
    volume character varying(50) COLLATE pg_catalog."default",
    issue character varying(50) COLLATE pg_catalog."default",
    pages character varying(100) COLLATE pg_catalog."default",
    editorial character varying(300) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    classification character varying(10) COLLATE pg_catalog."default",
    visibility character varying(50) COLLATE pg_catalog."default",
    research_group character varying(300) COLLATE pg_catalog."default",
    id_minciencias character varying(100) COLLATE pg_catalog."default",
    clase character varying(100) COLLATE pg_catalog."default",
    subtipo character varying(100) COLLATE pg_catalog."default",
    peso_absoluto double precision,
    peso_relativo double precision,
    peso_escalafon double precision,
    ventana character varying(20) COLLATE pg_catalog."default",
    abstract text COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    publisher character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT datos_abiertos_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.datos_abiertos_records.product_type
    IS 'Tipo de producto bibliográfico según Minciencias';

COMMENT ON COLUMN public.datos_abiertos_records.classification
    IS 'Clasificación revista/producto: A1, A2, B, C, D';

COMMENT ON COLUMN public.datos_abiertos_records.visibility
    IS 'Nacional, Internacional, No Aplica';

COMMENT ON COLUMN public.datos_abiertos_records.research_group
    IS 'Grupo de investigación que reporta el producto';

CREATE TABLE IF NOT EXISTS public.disciplinary_fields
(
    id serial NOT NULL,
    field_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    field_name_es character varying(200) COLLATE pg_catalog."default" NOT NULL,
    field_name_en character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT disciplinary_fields_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.disciplinary_fields.field_code
    IS 'CIENCIAS_SALUD, CIENCIAS_BASICAS, INGENIERIA, CIENCIAS_SOCIALES, ARTES_HUMANIDADES';

CREATE TABLE IF NOT EXISTS public.field_parameters
(
    id serial NOT NULL,
    field_id integer NOT NULL,
    parameter_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    parameter_type character varying(15) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT field_parameters_pkey PRIMARY KEY (id),
    CONSTRAINT uq_field_parameter UNIQUE (field_id, parameter_name)
);

COMMENT ON COLUMN public.field_parameters.parameter_name
    IS 'Nombre único del parámetro (ej: h_alto, weight_h_index, min_publications)';

COMMENT ON COLUMN public.field_parameters.parameter_type
    IS 'Tipo: float, int, bool, json, string';

COMMENT ON COLUMN public.field_parameters.value
    IS 'Valor almacenado como string (se convierte según parameter_type)';

CREATE TABLE IF NOT EXISTS public.google_scholar_records
(
    id serial NOT NULL,
    google_scholar_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    scholar_profile_id character varying(50) COLLATE pg_catalog."default",
    title character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    authors_json jsonb DEFAULT '[]'::jsonb,
    publication_year integer,
    publication_date date,
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    doi character varying(100) COLLATE pg_catalog."default",
    citation_count integer DEFAULT 0,
    citations_by_year jsonb DEFAULT '{}'::jsonb,
    url text COLLATE pg_catalog."default",
    status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    raw_data jsonb DEFAULT '{}'::jsonb,
    extracted_at timestamp without time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    canonical_publication_id integer,
    abstract text COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    publisher character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT google_scholar_records_pkey PRIMARY KEY (id),
    CONSTRAINT google_scholar_records_doi_key UNIQUE (doi),
    CONSTRAINT google_scholar_records_google_scholar_id_key UNIQUE (google_scholar_id)
);

CREATE TABLE IF NOT EXISTS public.gruplac_records
(
    id serial NOT NULL,
    gruplac_product_id character varying(255) COLLATE pg_catalog."default",
    gruplac_group_id character varying(100) COLLATE pg_catalog."default",
    group_name character varying(500) COLLATE pg_catalog."default",
    group_leader character varying(300) COLLATE pg_catalog."default",
    group_classification character varying(10) COLLATE pg_catalog."default",
    group_institution character varying(500) COLLATE pg_catalog."default",
    author_link_status character varying(100) COLLATE pg_catalog."default",
    author_role character varying(100) COLLATE pg_catalog."default",
    product_type character varying(100) COLLATE pg_catalog."default",
    abstract text COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    CONSTRAINT gruplac_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.gruplac_records.gruplac_product_id
    IS 'ID único del producto en GrupLAC';

COMMENT ON COLUMN public.gruplac_records.gruplac_group_id
    IS 'Código GrupLAC del grupo de investigación';

COMMENT ON COLUMN public.gruplac_records.group_name
    IS 'Nombre del grupo de investigación en GrupLAC';

COMMENT ON COLUMN public.gruplac_records.group_leader
    IS 'Nombre del líder del grupo de investigación';

COMMENT ON COLUMN public.gruplac_records.group_classification
    IS 'Clasificación Minciencias del grupo: A1, A, B, C, D, Sin clasificar';

COMMENT ON COLUMN public.gruplac_records.group_institution
    IS 'Institución a la que pertenece el grupo';

COMMENT ON COLUMN public.gruplac_records.author_link_status
    IS 'Estado de vinculación del investigador al grupo (ej: Activo, Inactivo)';

COMMENT ON COLUMN public.gruplac_records.author_role
    IS 'Rol del investigador en el grupo (Investigador, Estudiante, etc.)';

COMMENT ON COLUMN public.gruplac_records.product_type
    IS 'Tipo de producto según GrupLAC';

CREATE TABLE IF NOT EXISTS public.institutions
(
    id serial NOT NULL,
    ror_id character varying(100) COLLATE pg_catalog."default",
    name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT institutions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.journals
(
    id serial NOT NULL,
    issn character varying(20) COLLATE pg_catalog."default",
    name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    publisher character varying(300) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT journals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.openalex_records
(
    id serial NOT NULL,
    openalex_work_id character varying(255) COLLATE pg_catalog."default",
    pmid character varying(50) COLLATE pg_catalog."default",
    pmcid character varying(50) COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    abstract text COLLATE pg_catalog."default",
    keywords text COLLATE pg_catalog."default",
    concepts jsonb,
    topics jsonb,
    mesh_terms jsonb,
    oa_url character varying(1000) COLLATE pg_catalog."default",
    pdf_url character varying(1000) COLLATE pg_catalog."default",
    license character varying(100) COLLATE pg_catalog."default",
    referenced_works_count integer,
    apc_paid_usd integer,
    grants jsonb,
    publisher character varying(300) COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT openalex_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.openalex_records.openalex_work_id
    IS 'ID de OpenAlex, ej: https://openalex.org/W12345';

COMMENT ON COLUMN public.openalex_records.abstract
    IS 'Resumen reconstruido desde abstract_inverted_index';

COMMENT ON COLUMN public.openalex_records.keywords
    IS 'Palabras clave (campo keywords de OpenAlex 2024+)';

COMMENT ON COLUMN public.openalex_records.concepts
    IS '[{display_name, score, wikidata_id, level}]';

COMMENT ON COLUMN public.openalex_records.topics
    IS '[{display_name, score, domain, field, subfield}]';

COMMENT ON COLUMN public.openalex_records.mesh_terms
    IS 'Medical Subject Headings cuando viene de PubMed';

COMMENT ON COLUMN public.openalex_records.oa_url
    IS 'URL directa a versión open access';

COMMENT ON COLUMN public.openalex_records.pdf_url
    IS 'URL directa al PDF';

COMMENT ON COLUMN public.openalex_records.license
    IS 'Licencia: cc-by, cc-by-nc, publisher-specific-oa, etc.';

COMMENT ON COLUMN public.openalex_records.referenced_works_count
    IS 'Cantidad de referencias bibliográficas';

COMMENT ON COLUMN public.openalex_records.apc_paid_usd
    IS 'Cargo por procesamiento de artículo (APC) en USD';

COMMENT ON COLUMN public.openalex_records.grants
    IS '[{funder, funder_display_name, award_id}]';

CREATE TABLE IF NOT EXISTS public.possible_duplicate_pairs
(
    id serial NOT NULL,
    canonical_id_1 integer NOT NULL,
    canonical_id_2 integer NOT NULL,
    similarity_score double precision NOT NULL,
    match_method character varying(50) COLLATE pg_catalog."default" NOT NULL,
    detected_at timestamp with time zone NOT NULL DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    confidence_level character varying(20) COLLATE pg_catalog."default",
    reviewed_by character varying(200) COLLATE pg_catalog."default",
    reviewed_at timestamp with time zone,
    CONSTRAINT possible_duplicate_pairs_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dup_pair UNIQUE (canonical_id_1, canonical_id_2)
);

COMMENT ON COLUMN public.possible_duplicate_pairs.status
    IS 'pending | merged | dismissed';

CREATE TABLE IF NOT EXISTS public.publicacion_estados
(
    id serial NOT NULL,
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT publicacion_estados_pkey PRIMARY KEY (id),
    CONSTRAINT publicacion_estados_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.publication_authors
(
    id serial NOT NULL,
    publication_id integer NOT NULL,
    author_id integer NOT NULL,
    is_institutional boolean NOT NULL,
    author_position integer,
    role character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT publication_authors_pkey PRIMARY KEY (id),
    CONSTRAINT uq_pub_author UNIQUE (publication_id, author_id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_log
(
    id serial NOT NULL,
    source_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    source_record_id integer NOT NULL,
    canonical_publication_id integer,
    match_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    match_score double precision,
    match_details jsonb,
    action character varying(30) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT reconciliation_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.research_thresholds
(
    id serial NOT NULL,
    field_id integer NOT NULL,
    metric_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    value double precision NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT research_thresholds_pkey PRIMARY KEY (id),
    CONSTRAINT uq_field_metric UNIQUE (field_id, metric_name)
);

COMMENT ON COLUMN public.research_thresholds.metric_name
    IS 'h_alto, h_medio, cpp_alto, cpp_medio, pct_citados, pct_pico, concentracion_limite, ratio_hn_minimo';

CREATE TABLE IF NOT EXISTS public.researcher_credentials
(
    id serial NOT NULL,
    author_id integer NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at timestamp with time zone,
    last_login timestamp with time zone,
    expires_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT researcher_credentials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scopus_records
(
    id serial NOT NULL,
    scopus_doc_id character varying(100) COLLATE pg_catalog."default",
    volume character varying(50) COLLATE pg_catalog."default",
    issue character varying(50) COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    abstract text COLLATE pg_catalog."default",
    author_keywords text COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    eid character varying(100) COLLATE pg_catalog."default",
    pmid character varying(50) COLLATE pg_catalog."default",
    isbn character varying(30) COLLATE pg_catalog."default",
    index_keywords text COLLATE pg_catalog."default",
    subtype_description character varying(100) COLLATE pg_catalog."default",
    conference_name character varying(500) COLLATE pg_catalog."default",
    funding_agency character varying(300) COLLATE pg_catalog."default",
    funding_number character varying(200) COLLATE pg_catalog."default",
    publisher character varying(300) COLLATE pg_catalog."default",
    journal_coverage character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT scopus_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.scopus_records.scopus_doc_id
    IS 'Scopus document ID (dc:identifier sin prefijo)';

COMMENT ON COLUMN public.scopus_records.eid
    IS 'Electronic ID: 2-s2.0-XXXXXXXX';

COMMENT ON COLUMN public.scopus_records.pmid
    IS 'PubMed ID cruzado desde Scopus';

COMMENT ON COLUMN public.scopus_records.isbn
    IS 'ISBN para libros y capítulos de libro';

COMMENT ON COLUMN public.scopus_records.index_keywords
    IS 'Vocabulario controlado de Scopus (idxterms)';

COMMENT ON COLUMN public.scopus_records.subtype_description
    IS 'Article, Review, Conference Paper, Book Chapter, etc.';

COMMENT ON COLUMN public.scopus_records.conference_name
    IS 'Nombre de la conferencia (para conference papers)';

COMMENT ON COLUMN public.scopus_records.funding_agency
    IS 'Entidad financiadora reportada en Scopus';

COMMENT ON COLUMN public.scopus_records.funding_number
    IS 'Número o código del grant de financiación';

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.wos_records
(
    id serial NOT NULL,
    wos_uid character varying(100) COLLATE pg_catalog."default",
    dedup_hash character varying(64) COLLATE pg_catalog."default",
    doi character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    normalized_title text COLLATE pg_catalog."default",
    publication_year integer,
    authors_text text COLLATE pg_catalog."default",
    normalized_authors text COLLATE pg_catalog."default",
    publication_date character varying(20) COLLATE pg_catalog."default",
    publication_type character varying(100) COLLATE pg_catalog."default",
    source_journal character varying(500) COLLATE pg_catalog."default",
    issn character varying(20) COLLATE pg_catalog."default",
    language character varying(10) COLLATE pg_catalog."default",
    is_open_access boolean,
    oa_status character varying(50) COLLATE pg_catalog."default",
    citation_count integer NOT NULL,
    url character varying(1000) COLLATE pg_catalog."default",
    raw_data jsonb,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    match_type character varying(50) COLLATE pg_catalog."default",
    match_score double precision,
    reconciled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    canonical_publication_id integer,
    accession_number character varying(100) COLLATE pg_catalog."default",
    pmid character varying(50) COLLATE pg_catalog."default",
    volume character varying(50) COLLATE pg_catalog."default",
    issue character varying(50) COLLATE pg_catalog."default",
    page_range character varying(100) COLLATE pg_catalog."default",
    early_access_date character varying(20) COLLATE pg_catalog."default",
    issn_electronic character varying(20) COLLATE pg_catalog."default",
    abstract text COLLATE pg_catalog."default",
    author_keywords text COLLATE pg_catalog."default",
    wos_categories text COLLATE pg_catalog."default",
    research_areas text COLLATE pg_catalog."default",
    publisher character varying(300) COLLATE pg_catalog."default",
    conference_title character varying(500) COLLATE pg_catalog."default",
    times_cited_all_databases integer,
    citing_patents_count integer,
    funding_orgs jsonb,
    CONSTRAINT wos_records_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.wos_records.wos_uid
    IS 'WoS UID, ej: WOS:000123456789';

COMMENT ON COLUMN public.wos_records.accession_number
    IS 'Número de acceso interno WoS';

COMMENT ON COLUMN public.wos_records.early_access_date
    IS 'Fecha de publicación anticipada (Early Access)';

COMMENT ON COLUMN public.wos_records.issn_electronic
    IS 'ISSN de la versión electrónica';

COMMENT ON COLUMN public.wos_records.wos_categories
    IS 'Categorías Web of Science separadas por "; "';

COMMENT ON COLUMN public.wos_records.research_areas
    IS 'Áreas de investigación WoS separadas por "; "';

COMMENT ON COLUMN public.wos_records.times_cited_all_databases
    IS 'Citas contadas en todas las colecciones WoS';

COMMENT ON COLUMN public.wos_records.citing_patents_count
    IS 'Número de patentes que citan este artículo';

COMMENT ON COLUMN public.wos_records.funding_orgs
    IS '[{organization, grant_numbers:[]}]';

ALTER TABLE IF EXISTS public.author_aliases
    ADD CONSTRAINT author_aliases_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_author_aliases_author_id
    ON public.author_aliases(author_id);


ALTER TABLE IF EXISTS public.author_audit_log
    ADD CONSTRAINT author_audit_log_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_author_audit_author_id
    ON public.author_audit_log(author_id);


ALTER TABLE IF EXISTS public.author_conflicts
    ADD CONSTRAINT author_conflicts_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_author_conflicts_author_id
    ON public.author_conflicts(author_id);


ALTER TABLE IF EXISTS public.author_institutions
    ADD CONSTRAINT author_institutions_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.author_institutions
    ADD CONSTRAINT author_institutions_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institutions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.authors
    ADD CONSTRAINT authors_possible_duplicate_of_fkey FOREIGN KEY (possible_duplicate_of)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_authors_possible_dup
    ON public.authors(possible_duplicate_of);


ALTER TABLE IF EXISTS public.canonical_pub_open_data
    ADD CONSTRAINT canonical_pub_open_data_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_cpod_canon
    ON public.canonical_pub_open_data(canonical_publication_id);


ALTER TABLE IF EXISTS public.canonical_publications
    ADD CONSTRAINT canonical_publications_estado_publicacion_id_fkey FOREIGN KEY (estado_publicacion_id)
    REFERENCES public.publicacion_estados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.canonical_publications
    ADD CONSTRAINT canonical_publications_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_canonical_publications_journal_id
    ON public.canonical_publications(journal_id);


ALTER TABLE IF EXISTS public.clasificacion_minciencias
    ADD CONSTRAINT clasificacion_minciencias_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cvlac_records
    ADD CONSTRAINT cvlac_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_cvlac_records_canonical_publication_id
    ON public.cvlac_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.datos_abiertos_records
    ADD CONSTRAINT datos_abiertos_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_datos_abiertos_records_canonical_publication_id
    ON public.datos_abiertos_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.field_parameters
    ADD CONSTRAINT field_parameters_field_id_fkey FOREIGN KEY (field_id)
    REFERENCES public.disciplinary_fields (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_field_parameters_field_id
    ON public.field_parameters(field_id);


ALTER TABLE IF EXISTS public.google_scholar_records
    ADD CONSTRAINT google_scholar_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_google_scholar_canonical
    ON public.google_scholar_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.gruplac_records
    ADD CONSTRAINT gruplac_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_gruplac_records_canonical_publication_id
    ON public.gruplac_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.openalex_records
    ADD CONSTRAINT openalex_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_openalex_records_canonical_publication_id
    ON public.openalex_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.possible_duplicate_pairs
    ADD CONSTRAINT possible_duplicate_pairs_canonical_id_1_fkey FOREIGN KEY (canonical_id_1)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_possible_duplicate_pairs_canonical_id_1
    ON public.possible_duplicate_pairs(canonical_id_1);


ALTER TABLE IF EXISTS public.possible_duplicate_pairs
    ADD CONSTRAINT possible_duplicate_pairs_canonical_id_2_fkey FOREIGN KEY (canonical_id_2)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_possible_duplicate_pairs_canonical_id_2
    ON public.possible_duplicate_pairs(canonical_id_2);


ALTER TABLE IF EXISTS public.publication_authors
    ADD CONSTRAINT publication_authors_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_pub_authors_author
    ON public.publication_authors(author_id);


ALTER TABLE IF EXISTS public.publication_authors
    ADD CONSTRAINT publication_authors_publication_id_fkey FOREIGN KEY (publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_pub_authors_pub
    ON public.publication_authors(publication_id);


ALTER TABLE IF EXISTS public.reconciliation_log
    ADD CONSTRAINT reconciliation_log_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_reconciliation_log_canonical_publication_id
    ON public.reconciliation_log(canonical_publication_id);


ALTER TABLE IF EXISTS public.research_thresholds
    ADD CONSTRAINT research_thresholds_field_id_fkey FOREIGN KEY (field_id)
    REFERENCES public.disciplinary_fields (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_research_thresholds_field_id
    ON public.research_thresholds(field_id);


ALTER TABLE IF EXISTS public.researcher_credentials
    ADD CONSTRAINT researcher_credentials_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_researcher_credentials_author_id
    ON public.researcher_credentials(author_id);


ALTER TABLE IF EXISTS public.scopus_records
    ADD CONSTRAINT scopus_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_scopus_records_canonical_publication_id
    ON public.scopus_records(canonical_publication_id);


ALTER TABLE IF EXISTS public.wos_records
    ADD CONSTRAINT wos_records_canonical_publication_id_fkey FOREIGN KEY (canonical_publication_id)
    REFERENCES public.canonical_publications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_wos_records_canonical_publication_id
    ON public.wos_records(canonical_publication_id);

END;